# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Plugin\ParCatGML_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ParCatGML_dialog(object):
    def setupUi(self, ParCatGML_dialog):
        ParCatGML_dialog.setObjectName("ParCatGML_dialog")
        ParCatGML_dialog.resize(496, 466)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        ParCatGML_dialog.setFont(font)
        ParCatGML_dialog.setWindowTitle("Exportación parcelas a GML")
        self.verticalLayout = QtWidgets.QVBoxLayout(ParCatGML_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Logo = QtWidgets.QLabel(ParCatGML_dialog)
        self.Logo.setMinimumSize(QtCore.QSize(48, 48))
        self.Logo.setMaximumSize(QtCore.QSize(48, 48))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("ParCatGML.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.horizontalLayout_2.addWidget(self.Logo)
        self.label = QtWidgets.QLabel(ParCatGML_dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mun = QtWidgets.QLineEdit(ParCatGML_dialog)
        self.mun.setObjectName("mun")
        self.gridLayout.addWidget(self.mun, 3, 1, 1, 1)
        self.refcat = QtWidgets.QLineEdit(ParCatGML_dialog)
        self.refcat.setObjectName("refcat")
        self.gridLayout.addWidget(self.refcat, 1, 1, 1, 1)
        self.muni_lbl = QtWidgets.QLabel(ParCatGML_dialog)
        self.muni_lbl.setObjectName("muni_lbl")
        self.gridLayout.addWidget(self.muni_lbl, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ParCatGML_dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.deleg_lbl = QtWidgets.QLabel(ParCatGML_dialog)
        self.deleg_lbl.setObjectName("deleg_lbl")
        self.gridLayout.addWidget(self.deleg_lbl, 2, 0, 1, 1)
        self.num = QtWidgets.QLineEdit(ParCatGML_dialog)
        self.num.setObjectName("num")
        self.gridLayout.addWidget(self.num, 4, 1, 1, 1)
        self.area_lbl = QtWidgets.QLabel(ParCatGML_dialog)
        self.area_lbl.setObjectName("area_lbl")
        self.gridLayout.addWidget(self.area_lbl, 6, 0, 1, 1)
        self.pro = QtWidgets.QLineEdit(ParCatGML_dialog)
        self.pro.setObjectName("pro")
        self.gridLayout.addWidget(self.pro, 2, 1, 1, 1)
        self.Selec = QtWidgets.QTableWidget(ParCatGML_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Selec.setFont(font)
        self.Selec.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Selec.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.Selec.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Selec.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Selec.setWordWrap(False)
        self.Selec.setObjectName("Selec")
        self.Selec.setColumnCount(0)
        self.Selec.setRowCount(0)
        self.Selec.horizontalHeader().setDefaultSectionSize(20)
        self.Selec.horizontalHeader().setHighlightSections(False)
        self.Selec.horizontalHeader().setMinimumSectionSize(20)
        self.Selec.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.Selec, 0, 1, 1, 1)
        self.num_parcel_lbl = QtWidgets.QLabel(ParCatGML_dialog)
        self.num_parcel_lbl.setObjectName("num_parcel_lbl")
        self.gridLayout.addWidget(self.num_parcel_lbl, 4, 0, 1, 1)
        self.refcat_lbl = QtWidgets.QLabel(ParCatGML_dialog)
        self.refcat_lbl.setObjectName("refcat_lbl")
        self.gridLayout.addWidget(self.refcat_lbl, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.area = QtWidgets.QSpinBox(ParCatGML_dialog)
        self.area.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.area.setMaximum(999999999)
        self.area.setObjectName("area")
        self.horizontalLayout_6.addWidget(self.area)
        self.Canvi = QtWidgets.QPushButton(ParCatGML_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Canvi.sizePolicy().hasHeightForWidth())
        self.Canvi.setSizePolicy(sizePolicy)
        self.Canvi.setMinimumSize(QtCore.QSize(33, 29))
        self.Canvi.setMaximumSize(QtCore.QSize(33, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Canvi.setFont(font)
        self.Canvi.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("EditTable.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Canvi.setIcon(icon)
        self.Canvi.setAutoDefault(False)
        self.Canvi.setObjectName("Canvi")
        self.horizontalLayout_6.addWidget(self.Canvi)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(ParCatGML_dialog)
        self.label_3.setMinimumSize(QtCore.QSize(116, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.data = QtWidgets.QDateTimeEdit(ParCatGML_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data.sizePolicy().hasHeightForWidth())
        self.data.setSizePolicy(sizePolicy)
        self.data.setMinimumSize(QtCore.QSize(157, 25))
        self.data.setMaximumSize(QtCore.QSize(157, 25))
        self.data.setCalendarPopup(True)
        self.data.setObjectName("data")
        self.horizontalLayout_3.addWidget(self.data)
        self.label_5 = QtWidgets.QLabel(ParCatGML_dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.Inspire3 = QtWidgets.QRadioButton(ParCatGML_dialog)
        self.Inspire3.setObjectName("Inspire3")
        self.horizontalLayout_3.addWidget(self.Inspire3)
        self.Inspire4 = QtWidgets.QRadioButton(ParCatGML_dialog)
        self.Inspire4.setObjectName("Inspire4")
        self.horizontalLayout_3.addWidget(self.Inspire4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(ParCatGML_dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.desti = QtWidgets.QLineEdit(ParCatGML_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.desti.setFont(font)
        self.desti.setObjectName("desti")
        self.horizontalLayout_5.addWidget(self.desti)
        self.Carpeta = QtWidgets.QPushButton(ParCatGML_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Carpeta.sizePolicy().hasHeightForWidth())
        self.Carpeta.setSizePolicy(sizePolicy)
        self.Carpeta.setMinimumSize(QtCore.QSize(33, 29))
        self.Carpeta.setMaximumSize(QtCore.QSize(33, 29))
        self.Carpeta.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Carpeta.setIcon(icon1)
        self.Carpeta.setAutoDefault(False)
        self.Carpeta.setObjectName("Carpeta")
        self.horizontalLayout_5.addWidget(self.Carpeta)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Crear = QtWidgets.QPushButton(ParCatGML_dialog)
        self.Crear.setObjectName("Crear")
        self.horizontalLayout.addWidget(self.Crear)
        self.Tancar = QtWidgets.QPushButton(ParCatGML_dialog)
        self.Tancar.setObjectName("Tancar")
        self.horizontalLayout.addWidget(self.Tancar)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ParCatGML_dialog)
        self.Tancar.clicked.connect(ParCatGML_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ParCatGML_dialog)

    def retranslateUi(self, ParCatGML_dialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("ParCatGML_dialog", "Exportación parcelas catastrales\n"
"(formato INSPIRE GML CP)"))
        self.muni_lbl.setText(_translate("ParCatGML_dialog", "Municipio"))
        self.label_2.setText(_translate("ParCatGML_dialog", "Parcelas\n"
"seleccionadas"))
        self.deleg_lbl.setText(_translate("ParCatGML_dialog", "Delegación"))
        self.area_lbl.setText(_translate("ParCatGML_dialog", "Area (m²)"))
        self.num_parcel_lbl.setText(_translate("ParCatGML_dialog", "Numero parcela"))
        self.refcat_lbl.setText(_translate("ParCatGML_dialog", "Referència Cat."))
        self.label_3.setText(_translate("ParCatGML_dialog", "Fecha y hora"))
        self.data.setDisplayFormat(_translate("ParCatGML_dialog", "dd-MM-yyyy H:mm"))
        self.label_5.setText(_translate("ParCatGML_dialog", "   INSPIRE:"))
        self.Inspire3.setText(_translate("ParCatGML_dialog", "v3"))
        self.Inspire4.setText(_translate("ParCatGML_dialog", "v4"))
        self.label_4.setText(_translate("ParCatGML_dialog", "Carpeta destino"))
        self.Crear.setText(_translate("ParCatGML_dialog", "Crear GML"))
        self.Tancar.setText(_translate("ParCatGML_dialog", "Salir"))

